name: prune
channels:
  - conda-forge
  - pytorch
  - anaconda
  - defaults
dependencies:
  - numpy=1.20.2
  - pillow=8.2.0
  - python=3.8.10
  - pytorch=1.9.0
  - scipy=1.6.2
  - tensorboardx=2.2
  - torchvision=0.10.0
  - tqdm=4.61.1
